### PR TITLE
Corrected dict to typing.Dict at 11 instances

### PR DESCRIPTION
**Pull request by nihalshetty-boop**
I have changed `dict` to `typing.Dict` as requested at 11 files, including the original baseinspector.py and 10 other classes inheriting from `BaseInspector`. Checked for any other instances of `dict`, but these were the only ones found.

### CODE REVIEW

**Comment by nbirillo** [comment]
@nihalshetty-boop Thank you for your help! But you did not add `Dict` in the `imports` sections and so you have flake8 errors. 
```
from typing import Dict, List
```
Moreover, it is better to use a simple `Dict` in the functions, it is shorter and clearer.

**Comment by nihalshetty-boop** [comment]
@nbirillo I have reflected the changes regarding

> But you did not add Dict in the imports sections and so you have flake8 errors.

in flake8 as well as other files where found necessary. Also changed `typing.Dict` to `Dict` and redirected PR from `main` to `develop` branch as requested.

**Comment by nihalshetty-boop** [comment]
@nbirillo @vyahhi There are some conflicts which have appeared after redirecting the PR from `main` to `develop` branch. Please look into it.

**Comment by vyahhi** [comment]
@nihalshetty-boop your PR adds 1,576 lines and removes 1,288 lines. It's too many changes for a dozen of typing fixes. For example, in https://github.com/hyperskill/hyperstyle/pull/83/files#diff-e6dba513de176d39a1404b6f57d47120dfc4dc2fce36a00c64c3bc2949b82f14 you change 34 lines in the file instead of just 2 lines. Please minimize changes.

**Comment by nihalshetty-boop** [comment]
@vyahhi That happened because I wasn't able to add push the changes through the terminal, so I uploaded them to my forked repo. I'll close this PR and try submitting one again.

**Pull request closed without merging**
