### PR TITLE
Add whitelist for flake8-spellcheck

### PR DESCRIPTION
**Pull request by nbirillo**
**Issues**:
[Issue#67: "Possibly misspelt word: 'sqrt'" <- it shouldn't be showing up](https://github.com/hyperskill/hyperstyle/issues/67)

**Description**: Add whitelist for flake8-spellcheck

### CODE REVIEW

**Comment by andrvb** [comment]
It would be nice to add a test for this case.

**Comment by nbirillo** [comment]
@andrvb done

**Review by andrvb — APPROVED** [review]

**Comment by vyahhi** [comment]
@nbirillo @andrvb do we also need to increment the version number in `VERSION.md` in each PR into the main branch?

**Comment by andrvb** [comment]
Only if we want to deploy a PR to the production.

**Pull request merged**
