### PR TITLE
Corrected dict errors and added types for Dict

### PR DESCRIPTION
**Pull request by nihalshetty-boop**
**Issues**:
[Issue#82](https://github.com/hyperskill/hyperstyle/issues/82)

**Description**:
This new PR is a clone of `hyperskill:develop`. Fixed the conflicts arising in previous PRs due to the wrong target branch being used.
I have changed dict to Dict as requested in 11 files, including the original `baseinspector.py` and 10 other classes inheriting from `BaseInspector`. Added types for Dict: `Dict[str, Any]`. Checked for any other instances of dict, but these were the only ones found. Also added Dict in the import sections of the files where it was necessary.

Please let me know if there are any other issues of Good First Issue Label. I will be happy to contribute!

### CODE REVIEW

**Comment by GirZ0n** [comment]
@nihalshetty-boop Hi! You also need to import `Any` from `typing` :slightly_smiling_face:.

For example, here you use `Any`
https://github.com/hyperskill/hyperstyle/blob/a673b6ebb665b22eb086d9f10616c4c74ed7ec37/src/python/review/inspectors/base_inspector.py#L33

But did not import `Any` from `typing`
https://github.com/hyperskill/hyperstyle/blob/a673b6ebb665b22eb086d9f10616c4c74ed7ec37/src/python/review/inspectors/base_inspector.py#L3

**Comment by nihalshetty-boop** [comment]
@GirZ0n Great, it works now!

**Review by GirZ0n — APPROVED** [review]
Great. Thank you!

**Comment by GirZ0n** [comment]
@nihalshetty-boop Now waiting for a review from @nbirillo. Most likely on Monday the PR will be merged into develop.

**Review by nbirillo — APPROVED** [review]
Great! Thank you a lot!

**Pull request merged**
